name: CI with GHA

on:
  push:
    branches: 
    - main
    - features/*

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: ls -alh

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  
  deploy:
    runs-on: windows-latest
    steps:
      - name: Print Statement
        run: Write-Output "This is a deploy job meant to run a file from the build job"
